github:
  description: "Apache Sling Website"
  homepage: "https://sling.apache.org/"
  labels:
  - "sling"
  - "website"
  - "jbake"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
  features:
    issues: true
publish:
  whoami: "asf-site"
notifications:
  jira_options: "link"
