github:
  description: "Apache Sling Website"
  homepage: "https://sling.apache.org/"
  labels:
  - "sling"
  - "website"
  - "jbake"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
  features:
    issues: true
  pull_requests:
    del_branch_on_merge: true
  protected_branches:
    master: {}
publish:
  whoami: "asf-site"
notifications:
  jira_options: "link"
  pullrequests_bot_sonarcloud: "commits@sling.apache.org"
